### ISSUE TITLE
Embedded tags

### ISSUE THREAD

**Issue by Shusshu** [inversoft/prime-transformer#3]
How do you support embedded tags in a transformer or is that not supported at all?

e.g.: [B]Bold only - [I]bold italic[/I][/B]

**Comment by robotdan** [comment]
Yes, embedded tags are supported. Your example is correct.

`[b]bold only - [i]bold italic[/i][/b]`

With the following configuration:
  `b`  :   `<strong>${body}</strong>`
  `i`    :  `<em>${body}</em>`

Your example would then produce the following HTML:
`<strong>bold only - <em>bold italic</em></strong>`

**Comment by Shusshu** [comment]
What's the part of the transformer that actually make this work?

Because in my own transformer I get only bold applied to the full text ... maybe it's just the style that gets overridden

**Comment by robotdan** [comment]
I have lots of tests cases for embedded tags, so my guess is that if you're seeing a formatting issue, it is most likely related to the tag configuration or your style.

To understand what is happening, I'd have to know how your templates for `b` and `i` are configured.  Can you provide those two templates and the resulting HTML that gets produced?

**Comment by Shusshu** [comment]
I'm not using the HTML transformer,
I made my own transformer which creates Android spannables
https://gist.github.com/Shusshu/b4c0d5634e69adf9a22fa694cd853f28

**Comment by Shusshu** [comment]
Actually it goes 3 times in the TagNode

[b]bold only - [i]bold italic[/i][/b]
1. bold only - 
2. bold italic
3. bold only - bold italic

**Comment by Shusshu** [comment]
Nvm I found my issue, I converted my span into a string so I lost the span value linked to it.
Didn't convert your code properly ;)

**Comment by robotdan** [comment]
Ok, cool. Bummer that lambdas aren't supported yet in Android - it would be cool to add your transformer impl into mainline.

**Comment by Shusshu** [comment]
Actually they are supported if you use the new compiler "jack & jill" but it's not ready for prime time...

I could eventually bring back all the java 8 stuff I stripped out and make a pull request to bring it in your project but then we would need to have multiple modules so the android version wouldn't need to import the resources in an non-android way.

**Comment by robotdan** [comment]
Ok. I'd be happy to link to your fork for anyone looking for an Android impl.

**Comment by Shusshu** [comment]
Or we could put everything in your repo first in java 8 (as it is supported by Android but only if you use another toolchain which is not my case as that toolchain is not perfect yet)

In your repo using multiple module (dunno how to do that with savant)
We would need to move the html stuff out of the main module so we don't have any resources in the main module

then I can make a java 7 version under my fork

**Comment by robotdan** [comment]
That could work - can you point me at your fork and I'll take a look to see if it may be possible to merge your changes into master.

**Comment by Shusshu** [comment]
I haven't published my fork as I changed too many things (I had to get rid of the nodeConsumer, the TransformFunction too...)

The best would be if you could split your code into 2 module (core & html stuff)
Then I can make a PR with the android transformer in Java 8 in a new module
Once accepted I can make a fork with a downgraded version to java 7 of the core module + android transformer module
